log_wandb: False
# Dataset config
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
# RATING_FIELD: label
load_col:
    inter: [user_id, item_id, rating]
    # inter: [user_id, item_id, label]
    item: [item_id,movie_title,release_year,class]
    user: [user_id,age,gender,occupation,zip_code]
user_inter_num_interval: [40,200]

# Training and evaluation config
seed: 1128
epochs: 200
train_batch_size: 32
valid_metric: rmse

# Evaluate config
eval_args:
    group_by: task
    order: RO
    split: {'RS': [0.7,0.1,0.2]}
    mode : labeled

# Meta learning config
meta_args:
    support_num: 20
    query_num: none

# MeLU Parameters
embedding_size: 32
mlp_hidden_size: [64,64]
melu_args:
    local_lr: 0.0005
    lr: 0.005

# Metrics
# metrics: ['precision','recall','hit','ndcg']
metrics: ['rmse']
metric_decimal_place: 4
topk: 5